version: '3.9'
services:
  wordpress:
    image: tiemez/wordpress-openlitespeed
    platform: linux/amd64
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${PUB_PORT:-80}:80
      - ${PUB_PORT_SSL:-443}:443
    volumes:
      - wordpress:/var/www/html/:rw
      - ./wordpress/wp-content:/var/www/html/wp-content:rw
    restart: on-failure
networks:
  rp_wordpress:
    driver: bridge
volumes:
  wordpress:
    driver: local